# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee6a4250314c859a073ea461fd43400bc5330a3fa4ff70b60cc277079cdaf5af06281f3c0e1b6f6fb7ed37e00b05d9fc9c5d12d7a725640775d0905719985039

test:
  secret_key_base: 283e5742ba85ac354352d481aed41c079b76de9fa956db15c5247a7ddc8abcbf978440e6a5b22cbe5adce0cada2164239af913e246850fa26e5b8119591935be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
